import dotenv from "dotenv";

dotenv.config();

const { PORT, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST} =
  process.env;
export default {
  POSTGRES_HOST: POSTGRES_HOST,
  PORT: PORT,
  POSTGRES_PORT: POSTGRES_PORT,
  POSTGRES_DB: POSTGRES_DB,
  POSTGRES_USER: POSTGRES_USER,
  POSTGRES_PASSWORD: POSTGRES_PASSWORD
};